#!/usr/bin/env bash

cmdname=$(basename ${0})

################
# functions
################
function usage() {
    cat <<EOS
This is a things for generating speech bubble.
The "fkds" command comes from "FuKiDaShi" in Japanese.

Usage:
    ${cmdname} [OPTIONS] STRING

OPTIONS:
    -h                 Show this help text

EOS
}

################
# options
################
while getopts h OPT
do
  case ${OPT} in
    h)
      usage
      exit 0
      ;;
  esac
done

shift $(expr $OPTIND - 1)


################
# arguments
################
text=${1}

if [ "${text}" == "" ]; then
  echo "${cmdname}: STRING argument is required" >&2
  exit 1
fi


################
# main
################
body="＞　${text}　＜"

text_length=$(echo ${text} | wc -m)
text_byte=$(echo ${text} | wc -c)

if [ ${text_byte} -eq ${text_length} ]; then
  repeat_num=$(expr ${text_length} / 2 + 1)
else
  repeat_num=${text_length}
fi

header="＿$(yes '⅄_' | head -n ${repeat_num} | tr -d '\n')＿"
footer="￣$(yes 'Y^' | head -n ${repeat_num} | tr -d '\n')￣"

echo ${header}
echo ${body}
echo ${footer}
